### PR TITLE
Add ATO example of colored_tps

### PR DESCRIPTION
**Pull request by Andre601**
I'm well aware of `server_tps_1_colored` but perhaps people want to have their own colors, matching the color scheme of their server?

### CODE REVIEW

**Comment by CodeCrafter47** [comment]
Can you add a note that this requires PlaceholderAPI?

**Comment by Andre601** [comment]
> Can you add a note that this requires PlaceholderAPI?

There is a note, although it being rather minor

**Comment by CodeCrafter47** [comment]
I see. I suppose that will do.

**Comment by Andre601** [comment]
I just now added the note xD

**Pull request merged**
